openapi: 3.0.3

info:
  title: Phrase API Reference
  version: 2.0.0
  description: 
    $ref: './intro.md'

  contact:
    name: Phrase Support
    url: https://developers.phrase.com/api/
    email: support@phrase.com

  x-logo:
    url: "https://developers.phrase.com/images/phrase-logo.png"
    backgroundColor: "#0091eb"
    altText: "Phrase"

  termsOfService: 'https://phrase.com/terms/'

  license: 
    name: MIT
    url: https://choosealicense.com/licenses/mit/

servers:
  - url: https://api.phrase.com/v2

security:
  - Token: []
  - Basic: []

tags:
  - name: Spaces
    description: Everything about Space
  - name: Authorizations
    description: |
      The endpoints provided by the Authorizations API are **only accessible via Basic authentication with email and password**.

      When creating a new authorization, the new access token for this authorization will be returned in the immediate response but not later, due to security reasons. When accessing authorizations later, you will only see the last eight chars of the token in plain text (`token_last_eight`) and the SHA256 digest of the token for reference (`hashed_token`).

      For instructions on how authorization in general works, see our [Auth Guide](#authentication).

      ### Scopes

      When creating or updating an OAuth authorization, you can define a list of scopes to limit the access that can be performed by that authorization.

      #### Available Scopes

      <div class="table-responsive">
        <table class="basic-table">
          <thead>
            <tr class="basic-table__row basic-table__row--header">
              <th class="basic-table__cell basic-table__cell--header">Scope</th>
              <th class="basic-table__cell basic-table__cell--header">Description</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="basic-table__cell"><code>read</code></td>
              <td class="basic-table__cell">Read projects, locales, keys, translations, orders</td>
            </tr>
            <tr>
              <td class="basic-table__cell"><code>write</code></td>
              <td class="basic-table__cell">Write projects, locales, keys, translations but not orders</td>
            </tr>
            <tr>
              <td class="basic-table__cell"><code>orders.create</code></td>
              <td class="basic-table__cell">Create and confirm orders</td>
            </tr>
            <tr>
              <td class="basic-table__cell"><code>team.manage</code></td>
              <td class="basic-table__cell">Manage invitations and members</td>
            </tr>
          </tbody>
        </table>
      </div>

x-tagGroups:
  - name: Core Resources
    tags:
      - Projects
      - Locales
      - Keys
      - Translations
      - Uploads
      - Tags
      - Blacklisted Keys
      - Versions / History
  - name: Workflows
    tags:
      - Spaces
      - Jobs
      - Job Locales
      - Comments
      - Branches
  - name: Quality
    tags:
      - Glossaries
      - Glossary Terms
      - Glossary Term Translations
  - name: Integrations
    tags:
      - Bitbucket Sync
      - GitLab Sync
      - Webhooks
      - Distributions
      - Releases
  - name: Ordering
    tags:
      - Orders
      - Style guides
  - name: User management
    tags:
      - Authorizations
      - Users
      - Accounts
      - Members
      - Invitations
  - name: Screenshots
    tags:
      - Screenshots
      - Screenshot Markers
  - name: Misc
    tags:
      - Formats

components:
  securitySchemes:
    Token:
      type: apiKey
      in: header
      name: Authorization
      description: Enter your token in the format **token TOKEN**
    Basic:
      type: http
      scheme: basic

  headers:
    $ref: "./headers.yaml"

  schemas:
    $ref: "./schemas.yaml#/schemas"

  parameters:
    $ref: "./parameters.yaml"

  responses:
    $ref: "./responses.yaml"

paths:
  $ref: "./paths.yaml"
