[build]
  publish = "output/"
  functions = ""

[[redirects]]
  from = "http://com-phraseapp-developers.netlify.com/*"
  to = "https://developers.phrase.com/api/"
  status = 301
  force = true

[[redirects]]
  from = "https://com-phraseapp-developers.netlify.com/*"
  to = "https://developers.phrase.com/api/"
  status = 301
  force = true

[[redirects]]
  from = "http://developers.phraseapp.com/*"
  to = "https://developers.phrase.com/api/"
  status = 301
  force = true

[[redirects]]
  from = "https://developers.phraseapp.com/*"
  to = "https://developers.phrase.com/api/"
  status = 301
  force = true

[[redirects]]
  from = "http://developers.phrase.com/*"
  to = "https://developers.phrase.com/api/"
  status = 301
  force = true

[[redirects]]
  from = "https://developers.phrase.com/*"
  to = "https://developers.phrase.com/api/"
  status = 301
  force = false
